components:
  schemas:
    AcceptResPegOut:
      properties:
        signature:
          example: '0x0 description:'
          type: string
      type: object
    AddCollateralRequest:
      properties:
        amount:
          description: Amount to add to the collateral
          example: 100000000000
          type: integer
        lpRskAddress:
          description: Liquidity Provider RSK Address
          example: "0x0"
          type: string
      type: object
    BuildRefundPegOutPayloadRequest:
      properties:
        btcTxHash:
          description: BtcTxHash
          example: "0x0"
          type: string
        derivationAddress:
          description: DerivationAddress
          example: "0x0"
          type: string
        quoteHash:
          description: QuoteHash
          example: "0x0"
          type: string
      type: object
    BuildRefundPegOutPayloadResponse:
      properties:
        merkleBranchHashes:
          description: MerkleBranchHashes
          example: invalid example
          items:
            type: string
          type: array
        merkleBranchPath:
          description: MerkleBranchPath
          example: 0
          type: integer
        quote:
          description: Quote
          example: invalid example
          type: object
      type: object
    ChangeStatusRequest:
      properties:
        providerId:
          type: integer
        status:
          type: boolean
      type: object
    PeginQuoteDTO:
      properties:
        agreementTimestamp:
          type: integer
        btcRefundAddr:
          type: string
        callFee:
          type: integer
        callOnRegister:
          type: boolean
        confirmations:
          type: integer
        contractAddr:
          type: string
        data:
          type: string
        fedBTCAddr:
          type: string
        gasLimit:
          type: integer
        lbcAddr:
          type: string
        lpBTCAddr:
          type: string
        lpCallTime:
          type: integer
        lpRSKAddr:
          type: string
        nonce:
          type: integer
        penaltyFee:
          type: integer
        rskRefundAddr:
          type: string
        timeForDeposit:
          type: integer
        value:
          type: integer
      required:
      - fedBTCAddr
      - lbcAddr
      - lpRSKAddr
      - btcRefundAddr
      - rskRefundAddr
      - lpBTCAddr
      - callFee
      - penaltyFee
      - contractAddr
      - data
      - gasLimit
      - nonce
      - value
      - agreementTimestamp
      - timeForDeposit
      - lpCallTime
      - confirmations
      - callOnRegister
      type: object
    ProviderDTO:
      properties:
        acceptedQuoteExpiration:
          description: Accepted quote expiration time in seconds
          example: 3600
          type: integer
        apiBaseUrl:
          description: Provider API base URL
          example: https://api.example.com
          type: string
        fee:
          description: Provider fee
          example: 100000000000000000
          type: integer
        id:
          description: Provider id
          example: 1
          type: integer
        maxTransactionValue:
          description: Maximum transaction value
          example: 1000000000000000000
          type: integer
        minTransactionValue:
          description: Minimum transaction value
          example: 100000000
          type: integer
        name:
          description: Provider name
          example: Default Pegin Provider
          type: string
        provider:
          description: Provider address
          example: "0x0000000000000000000000000000000000000000"
          type: string
        quoteExpiration:
          description: Quote expiration time in seconds
          example: 3600
          type: integer
        status:
          description: Provider status
          example: true
          type: boolean
      required:
      - id
      - provider
      - name
      - fee
      - quoteExpiration
      - acceptedQuoteExpiration
      - minTransactionValue
      - maxTransactionValue
      - apiBaseUrl
      - status
      type: object
    ProviderRegisterRequest:
      properties:
        acceptedQuoteExpiration:
          type: integer
        apiBaseUrl:
          type: string
        fee:
          type: integer
        maxTransactionValue:
          type: integer
        minTransactionValue:
          type: integer
        name:
          type: string
        quoteExpiration:
          type: integer
        status:
          type: boolean
      type: object
    ProviderStatusChangeStatus:
      properties:
        Status:
          description: Returned Status
          example: Provider Updated Successfully
          type: string
      type: object
    Quote:
      properties:
        agreementTimestamp:
          type: integer
        callFee:
          type: integer
        depositConfirmations:
          type: integer
        depositDateLimit:
          type: integer
        expireBlocks:
          type: integer
        expireDate:
          type: integer
        lbcAddress:
          type: string
        liquidityProviderRskAddress:
          type: string
        nonce:
          type: integer
        penaltyFee:
          type: integer
        rskRefundAddress:
          type: string
        transferConfirmations:
          type: integer
        transferTime:
          type: integer
        value:
          type: integer
      type: object
    QuotePegOutRequest:
      properties:
        bitcoinRefundAddress:
          example: '0x0 description:'
          type: string
        from:
          example: '0x0 description:'
          type: string
        rskRefundAddress:
          example: '0x0 description:'
          type: string
        valueToTransfer:
          description: ValueToTransfer
          example: 10000000000000
          type: integer
      type: object
    QuotePegOutResponse:
      properties:
        derivationAddress:
          example: '0x0 description:'
          type: string
        quote:
          example: invalid example
          type: object
        quoteHash:
          example: '0x0 description:'
          type: string
      type: object
    QuoteRequest:
      properties:
        bitcoinRefundAddress:
          description: BitcoinRefundAddress
          example: "0x0"
          type: string
        callContractArguments:
          description: CallContractArguments
          example: "0x0"
          type: string
        callEoaOrContractAddress:
          description: CallEoaOrContractAddress
          example: "0x0"
          type: string
        lpAddress:
          description: LpAddress
          example: "0x0"
          type: string
        rskRefundAddress:
          description: RskRefundAddress
          example: "0x0"
          type: string
        valueToTransfer:
          description: ValueToTransfer
          example: 0
          type: integer
      required:
      - callEoaOrContractAddress
      - callContractArguments
      - valueToTransfer
      - rskRefundAddress
      - lpAddress
      - bitcoinRefundAddress
      type: object
    QuoteReturn:
      properties:
        quote:
          $ref: '#/components/schemas/PeginQuoteDTO'
          type: object
        quoteHash:
          type: string
      required:
      - quote
      - quoteHash
      type: object
    RegistrationStatus:
      properties:
        Status:
          description: Returned Status
          example: Provider Created Successfully
          type: string
      type: object
    SenBTCRequest:
      properties:
        address:
          description: Address to send BTC to
          example: "0x0"
          type: string
        amount:
          description: Amount to send BTC to address
          example: 100000000000
          type: integer
      type: object
    SenBTCResponse:
      properties:
        txHash:
          description: TxHash of the BTC transaction sent to the address
          example: "0x0"
          type: string
      type: object
    acceptReq:
      properties:
        quoteHash:
          example: '0x0 description:'
          type: string
      type: object
    acceptReqPegout:
      properties:
        derivationAddress:
          example: '0x0 description:'
          type: string
        quoteHash:
          example: '0x0 description:'
          type: string
      type: object
    acceptRes:
      properties:
        bitcoinDepositAddressHash:
          description: BitcoinDepositAddressHash
          example: "0x0"
          type: string
        signature:
          description: Signature
          example: "0x0"
          type: string
      required:
      - signature
      - bitcoinDepositAddressHash
      type: object
    healthRes:
      properties:
        services:
          description: LPS Services Status
          example:
            btc: ok
            db: ok
            rsk: ok
          type: object
        status:
          description: Overall LPS Health Status
          example: ok
          type: string
      type: object
    pegout.Quote:
      properties:
        agreementTimestamp:
          type: integer
        callFee:
          type: integer
        depositConfirmations:
          type: integer
        depositDateLimit:
          type: integer
        expireBlocks:
          type: integer
        expireDate:
          type: integer
        lbcAddress:
          type: string
        liquidityProviderRskAddress:
          type: string
        nonce:
          type: integer
        penaltyFee:
          type: integer
        rskRefundAddress:
          type: string
        transferConfirmations:
          type: integer
        transferTime:
          type: integer
        value:
          type: integer
      type: object
    services:
      properties:
        btc:
          type: string
        db:
          type: string
        rsk:
          type: string
      type: object
  securitySchemes:
    AuthorizationHeader:
      description: Input your token
      scheme: bearer
      type: http
info:
  title: Liquidity Provider Server
  version: "0.5"
openapi: 3.0.0
paths:
  /addCollateral:
    post:
      description: ' Adds Collateral'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCollateralRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SenBTCResponse'
          description: ""
      summary: Add Collateral
  /getProviders:
    get:
      description: ' Returns a list of providers.'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderDTO'
          description: ""
      summary: Get Providers
  /health:
    get:
      description: ' Returns server health.'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthRes'
          description: ""
      summary: Health
  /pegin/acceptQuote:
    post:
      description: ' Accepts Quote'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/acceptReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/acceptRes'
          description: ""
      summary: Accept Quote
  /pegin/getQuote:
    post:
      description: ' Gets Pegin Quote'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteReturn'
          description: ""
      summary: Pegin GetQuote
  /pegout/acceptQuote:
    post:
      description: ' Accepts Quote Pegout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/acceptReqPegout'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptResPegOut'
          description: ""
      summary: Accept Quote Pegout
  /pegout/getQuotes:
    post:
      description: ' Gets Pegout Quote'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuotePegOutRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotePegOutResponse'
          description: ""
      summary: Pegout GetQuote
  /pegout/refundPegOut:
    post:
      description: ' Refunds Pegout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuildRefundPegOutPayloadRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildRefundPegOutPayloadResponse'
          description: ""
      summary: Refund Pegout
  /pegout/sendBTC:
    post:
      description: ' Sends BTC'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SenBTCRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SenBTCResponse'
          description: ""
      summary: Send BTC
  /provider/changeStatus:
    post:
      description: ' Changes the status of the provider'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeStatusRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderStatusChangeStatus'
          description: ""
      summary: Change Provider Status
  /provider/register:
    post:
      description: ' Registers New Provider'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProviderRegisterRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationStatus'
          description: ""
      summary: Register Provider
security:
- AuthorizationHeader:
  - read
  - write
servers:
- description: ' Testnet'
  url: https://flyover-lps.testnet.rsk.co
- description: ' Mainnet'
  url: https://flyover-lps.mainnet.rifcomputing.net
