version: "3"
services:
  bitcoind:
    build: bitcoind
    image: bitcond:latest
    container_name: bitcoind01
    ports:
      - "18443:18443"
      - "18444:18444"
    networks:
      - net_lps
    command: ["-rpcuser=test", "-rpcpassword=test", "-addresstype=legacy", "-regtest", "-printtoconsole", "-server",
              "-txindex", "-deprecatedrpc=signrawtransaction", "-deprecatedrpc=accounts",
              "-rpcbind=0.0.0.0", "-rpcallowip=0.0.0.0/0"]

  rskj:
    build: rskj
    image: rskj:latest
    container_name: rskj01
    ports:
      - "4444:4444"
    networks:
      - net_lps
    command: [ "--regtest" ]
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://rskj:4444 -X POST -H \"Content-Type: application/json\" -d '{\"jsonrpc\":\"2.0\",\"method\":\"eth_chainId\",\"params\": [],\"id\":1}'"]
      interval: 6s
      timeout: 10s
      retries: 10

  lbc-deployer:
    build: lbc-deployer
    image: lbc-deployer:latest
    container_name: lbc-deployer01
    environment:
      - LBC_ADDR
    depends_on:
      - rskj
    volumes:
      - ${PWD}/volumes/lbc-deployer/contracts:/contracts
    networks:
      - net_lps

  lps:
    build:
      context: ../
      dockerfile: docker-compose/lps/Dockerfile
    image: lps:latest
    container_name: lps01
    environment:
      - LIQUIDITY_PROVIDER_RSK_ADDR
      - LIQUIDITY_PROVIDER_RSK_KEY
      - LIQUIDITY_PROVIDER_RSK_KEY_PASS
      - LBC_ADDR
    depends_on:
      - bitcoind
      - rskj
      - lbc-deployer
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/volumes/lps/logs:/lps/logs
      - ${PWD}/volumes/lbc-deployer/contracts:/lps/contracts
    networks:
      - net_lps

networks:
  net_lps:
    driver: "bridge"
