version: "3.7"
services:
  lps:
    logging:
      driver: loki
      options:
       loki-url: '**REMOVED**/loki/api/v1/push'
       loki-external-labels: job=docker,container=lps,host=flyover-01.aws-us-east-1.mainnet.flyover.rif.technology
