name: LPS E2E test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - QA-Test
      - Stable-Test
      - master
      - feature/GBI-1861

jobs:
  e2e-test:
    name: Server initialization and health check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Update env file
        run: cd docker-compose/local/ && ./gh-action-env.sh ${{ secrets.GITHUB_TOKEN }}

      - name: Building LPS environment...
        run: cd docker-compose/local/ && LPS_STAGE=regtest sh lps-env.sh up

      - name: Checking LPS health...
        run: curl -X GET http://localhost:8080/health

      - name: Shutting LPS environment down...
        run: cd docker-compose/local/ && LPS_STAGE=regtest sh lps-env.sh down
