name: LPS E2E test

on:
  push:
    branches: [ QA-Test, Stable-Test, master ]
  pull_request:
    branches: [ QA-Test, Stable-Test, master ]

jobs:
  e2e-test:
    name: Server initialization and health check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'

      - name: Update env file
        run: cd docker-compose/local/ && ./gh-action-env.sh ${{ secrets.GITHUB_TOKEN }}

      - name: Building LPS environment...
        run: cd docker-compose/local/ && LPS_STAGE=regtest sh lps-env.sh up

      - name: Checking LPS health...
        run: curl -X GET http://localhost:8080/health

      - name: Shutting LPS environment down...
        run: cd docker-compose/local/ && LPS_STAGE=regtest sh lps-env.sh down
