---
name: liquidity provider server TESTNET deploy

on:
  push:
    branches:
      - stable-test
      - devops/concourse-pipeline

jobs:
  deploy-liquidity:
    name: deploys liquidity server
    runs-on: ubuntu-latest
    environment:
      name: testnet

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flyover-testnet
          IMAGE_TAG: latest-stabletest
        run: |
          aws configure set region us-east-1
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 094889878379.dkr.ecr.us-east-1.amazonaws.com/flyover-testnet
          docker build -f docker-compose/lps/Dockerfile -t 094889878379.dkr.ecr.us-east-1.amazonaws.com/flyover-testnet:$IMAGE_TAG .
          docker push 094889878379.dkr.ecr.us-east-1.amazonaws.com/flyover-testnet:$IMAGE_TAG
          